name: Upload Files
name: Upload File

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Curl Command
        run: |
          ping -c 1 www.google.com
          curl -X POST -F "file=@/file.txt" https://Mixer2404.github.io
