name: Upload Files

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: uploaded-files
          path: uploads
